const maxsulotlar = [
    {
        id: 1,
        tur: "Sabzovot",
        narx: "6000",
        nom: "Kartoshka",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 2,
        tur: "Sabzovot",
        narx: "5000",
        nom: "Sabzi",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 3,
        tur: "Sabzovot",
        narx: "3000",
        nom: "Piyoz",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 4,
        tur: "Sabzovot",
        narx: "15000",
        nom: "Pomidor",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 5,
        tur: "Sabzovot",
        narx: "12000",
        nom: "Bodring",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 6,
        tur: "Sabzovot",
        narx: "7000",
        nom: "Karam",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 7,
        tur: "Meva",
        narx: "15000",
        nom: "Olma",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 8,
        tur: "Meva",
        narx: "16000",
        nom: "Banan",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 9,
        tur: "Meva",
        narx: "20000",
        nom: "Limon",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 10,
        tur: "Meva",
        narx: "17000",
        nom: "Mandarin",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 11,
        tur: "Meva",
        narx: "30000",
        nom: "Nok",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 12,
        tur: "Meva",
        narx: "25000",
        nom: "Anor",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 13,
        tur: "Go`sht va parranda",
        narx: "70000",
        nom: "Mol go`shti",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 14,
        tur: "Go`sht va parranda",
        narx: "60000",
        nom: "Qo`y go`shti",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 15,
        tur: "Go`sht va parranda",
        narx: "30000",
        nom: "Tovuq go`shti",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 16,
        tur: "Go`sht va parranda",
        narx: "50000",
        nom: "Kurka go`shti",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 17,
        tur: "Go`sht va parranda",
        narx: "85000",
        nom: "Lahm mol go`shti",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 18,
        tur: "Go`sht va parranda",
        narx: "75000",
        nom: "Broyler tovug`i",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 19,
        tur: "Ichimlik",
        narx: "10000",
        nom: "Cola",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 20,
        tur: "Ichimlik",
        narx: "9000",
        nom: "Fanta",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 21,
        tur: "Ichimlik",
        narx: "10000",
        nom: "Pepsi",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 22,
        tur: "Ichimlik",
        narx: "12000",
        nom: "Dena sharbati",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 23,
        tur: "Ichimlik",
        narx: "11000",
        nom: "Bliss sharbati",
        rasmi: "./Assets/images/havas-logo.jpg",
    },
    {
        id: 24,
        tur: "Ichimlik",
        narx: "10000",
        nom: "Сочная долина sharbati",
        rasmi: "./Assets/images/havas-logo.jpg",
    },

]